# .github/workflows/ruby.yml
name: "[RD Station] Run Tests - Ruby"

on:
  push:
    branches: ['main']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Run Tests
        run: |
          cd ruby
          ruby customer_success_balancing.rb